---
# tasks file for install_PaceMaker
#- name: Enable High Availability repository
 # ansible.builtin.command: apt config-manager --set-enabled highavailability

- name: install PaceMaker and required packages
  apt:
    name:
      - pacemaker
      - pcs
      - psmisc
      - policycoreutils-python-utils
    state: present

- name: Allow PCS port
  ansible.posix.firewalld:
    port: 2224/tcp
    permanent: true
    state: enabled

- name: Allow Corosync cluster communication
  ansible.posix.firewalld:
    port: 5403/tcp
    permanent: true
    state: enabled

- name: Allow Corosync UDP traffic
  ansible.posix.firewalld:
    port: 5405/udp
    permanent: true
    state: enabled

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload


- name: enable and start services
  ansible.builtin.systemd:
    name: pcsd
    enabled: true
    state: started
    
#- name: Selinux permissibve
 ### state: permissive

