---
# tasks file for install_apache2
- name: Install apache httpd   
  ansible.builtin.apt:
    name: apache2
    state: present

- name: ensure apache2 is running
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

- name: Ensure server-status.conf exists
  ansible.builtin.file:
    path: /etc/apache2/conf-available/server-status.conf
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Configure Apache server-status block
  ansible.builtin.blockinfile:
    path: /etc/apache2/conf-available/server-status.conf
    block: |
      <Location /server-status>
        SetHandler server-status
        Require local
      </Location>

- name: Reload Apache to apply server-status config
  ansible.builtin.service:
    name: apache2
    state: reloaded