---
# tasks file for conf_PaceMaker
- name: hacluster user password
  ansible.builtin.user:
    name: hacluster
    password: "{{ hacluster_password_hashed }}"

- name: Authenticate pcs
  ansible.builtin.command: >
    pcs host auth node1hb node2hb -u hacluster -p {{ hacluster_password_plain }}
  when: inventory_hostname == "node1"

- name: setup cluster
  ansible.builtin.command: >
    pcs cluster setup mycluster node1hb node2hb
  when: inventory_hostname == "node1"

- name: start the cluster
  ansible.builtin.command: >
    pcs cluster start --all
  when: inventory_hostname == "node1"

- name: enable cluster
  ansible.builtin.command: >
    pcs cluster enable --all
  when: inventory_hostname == "node1"

- name:  Verify Corosync Installation
  ansible.builtin.command: >
    corosync-cfgtool -s
  when: inventory_hostname == "node1"